#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By header with the server hostname
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y nginx
HOSTNAME=$(hostname)
cat > /etc/nginx/sites-available/default << CONF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    add_header X-Served-By $HOSTNAME;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location / {
        try_files \$uri \$uri/ =404;
    }
}
CONF
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "Holberton School" > /var/www/html/index.html
service nginx restart || service nginx start || /etc/init.d/nginx restart || /etc/init.d/nginx start || nginx
