#!/usr/bin/env bash
# Installs nginx and configures it to serve a page containing "Holberton School"
apt-get update -y > /dev/null 2>&1
apt-get install nginx -y > /dev/null 2>&1
rm -f /var/www/html/index.nginx-debian.html
echo "Holberton School" | tee /var/www/html/index.html > /dev/null
service nginx restart > /dev/null 2>&1