#!/usr/bin/env bash
# Install nginx web server
sudo apt update -y > /dev/null 2>&1
sudo apt install nginx -y > /dev/null 2>&1
sudo rm -f /var/www/html/index.nginx-debian.html
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null
service nginx restart > /dev/null 2>&1