#!/usr/bin/env bash
# Installs nginx and configures it to serve a page containing message "Holberton School"
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
