#!/usr/bin/env bash
# Installs nginx and configures a 301 redirect for /redirect_me
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.html
sed -i '/server_name _;/a\    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default
service nginx restart
