#!/usr/bin/env bash
# Installs nginx and configures a 301 redirect for /redirect_me
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y nginx
cat > /etc/nginx/sites-available/default << 'CONF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    location / {
        return 200 "Holberton School";
    }
}
CONF
service nginx restart
