#!/usr/bin/env bash
# Installs nginx and configures a custom 404 page and a redirect
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y nginx
echo "Ceci n'est pas une page" > /var/www/html/404.html
cat > /etc/nginx/sites-available/default << 'CONF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location / {
        try_files $uri $uri/ =404;
    }
}
CONF
echo "Holberton School" > /var/www/html/index.html
service nginx restart
